### ISSUE TITLE
Batch process

### ISSUE THREAD

**Issue by Mr-Milk** [jeremymcrae/liftover#10]
Hi, thanks for developing such a useful package. Could you support batch processing to convert many coordinates at the same time? Doing for-loop in Python to convert many is very slow.

Something like

```python
chrom_list = ['chr1', 'chr2', 'chr1']
pos_list = [123123123, 234534, 34623452]
converter.convert_coordinate_batch(chrom_list, pos_list)
```

**Comment by jeremymcrae** [comment]
Hi, thanks for your comment! Can I check what you mean by many coordinates? This package should handle ~1 million coordinates per second, I didn't expect anyone would need something faster than that. Mostly I've found the slow bit is loading sites to lift.

See code below benchmarking 1 million coordinate conversions with random coordinates. This takes 3.2 seconds, but 2 seconds of that is selecting a random site to convert.

```python
import random
import time

from liftover import get_lifter

CHROMS = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 
          '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X']
MAX_POS = 50000000

lifter = get_lifter('hg18', 'hg19')

time_a = time.time()
for x in range(1000000):
    chrom = random.choice(CHROMS)
    pos = random.randint(1, MAX_POS)
    new_coords = lifter[chrom][pos]

time_b = time.time()
print(time_b - time_a)
>>> 3.2
```

**Comment by Mr-Milk** [comment]
Hi, thanks for the reply. I was transforming an SNP file with > 100 million positions, so it took quite a long time. I think the time usage is fine since the transformation step only needs to run one time. Still, it would be good to have a faster one😄

**Comment by jeremymcrae** [comment]
Hmm, I think I'll leave it as is then. I'm sympathetic to your position, I just think it could be tricky getting it to work. 

I don't think there's any way of getting around iterating over the coordinates? A for-loop has to occur at some point, whether it's in your code, or internal to some function.

The underlying c++ lifting code runs quickly, in fact a good portion of the python function call occurs in the dictionary lookup for the chromosome, and later parsing of the chromosome string from c++ call. So there might be scope to avoid some of that, but it could be difficult.
