### ISSUE TITLE
What to infer from return of an empty list?

### ISSUE THREAD

**Issue by mvinyard** [jeremymcrae/liftover#14]
```python
import liftover
liftover.__version__
```
>'1.1.13'

```python

lifter = liftover.get_lifter("hg19", "hg38")
def _lift(row):
    chrom = row[0]

    print("Input chrom: {}".format(chrom))
    print("Input position: {}".format(row[1]))
    
    print(lifter[chrom][row[1]], end="\n\n")

```
```
[out]:

Input chrom: chr1
Input position: 1583534
[('chr1', 1715324, '+')]

Input chrom: chr1
Input position: 1583534
[('chr1', 1715324, '+')]

Input chrom: chr1
Input position: 1583627
[('chr1', 1715417, '+')]

Input chrom: chr1
Input position: 1583654
[]
```

You can see that the up until the final input position, the output of the lifter is as expected. However, this position returns an empty list. Is there any meaning to infer from this? Or am I perhaps doing something else that the program wasn't expecting? Thanks for any help you may be able to provide!

**Comment by jeremymcrae** [comment]
That's a site which cannot be lifted between those genome builds - the underlying chain file does not include that location for conversion. I checked this with the UCSC liftover webtool and that gives the same result for those sites. I BLATted the sequence around chr1:1583654, and while the sequence aligns fairly cleanly between hg19->hg38, it looks like the bases in the region chr1:1583645-1583686 fail to lift due to minor mismatches in the sequences between builds.

**Comment by mvinyard** [comment]
Thank you for this kind response and investigation, @jeremymcrae! I very much appreciate the explanation. As an expert in this area, I wonder what you might suggest doing in this scenario? I ended up using the UCSC liftOver CLI and my guess is these sites were just considered "unmapped". Didn't know if you had another solution in mind. Either way - thank you for the explanation.

**Comment by jeremymcrae** [comment]
it depends on how badly you want to retain the site. I generally drop those sites, but a crude approach to retain more would be realign the sequence around the site to your desired genome build, and determine the coords from that (if possible). Could be tricky though, you'd have to account for mismatches and potentially other edge cases. 

But if you only have a tiny fraction which do not lift, it's easier to drop them, as their absence shouldn't alter any analytical outcome.
