### ISSUE TITLE
Difference in output given identical chain file and coordinates with pyliftover

### ISSUE THREAD

**Issue by zhemingfan** [jeremymcrae/liftover#15]
Hi @jeremymcrae ,

Thank you for releasing this quicker version of pyliftOver. 

I noticed that using the [T2T -> CHR38 chain file](https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/chain/v1_nflo/chm13v2-grch38.chain), two different positions are given with the same chain files between liftover and pyliftover.

```
from liftover import ChainFile
from pyliftover import LiftOver

converter = ChainFile('chm13v2-grch38.chain.gz', 't2t', 'hg38')
print(converter['chr1'][1000000])  # outputs: [('chr1', 1573376, '+')]

converter_pyliftover = LiftOver('chm13v2-grch38.chain.gz')
print(converter_pyliftover.convert_coordinate('chr1', 1000000, '+')) # outputs: [('chr1', 1565496, '+', 255)]
```

What's the reason behind this behaviour, and which output is correct based on the chain file?

**Comment by jeremymcrae** [comment]
My code expected the alignment data lines to be tab-separated (the lines with three fields). I've updated my code to allow using spaces as the field separator, which now gives the same result as pyliftover when using your chain file. I've pushed a new version to pypi, installing that should fix the problem.

Thanks for pointing this out!
