### ISSUE TITLE
Temp directory location (error) -> option needed

### ISSUE THREAD

**Issue by mbaudis** [jeremymcrae/liftover#16]
When running as part of a (web) service the library may fail due the default for the temporary directory. E.g. when called from inside `/Library/WebServer/cgi-bin/bycon/beaconServer/aggregator.py` the `converter` fails on `os.mkdir(cache)`
=> `Permission denied: '/Library/WebServer/.liftover'`

A solution would be to provide an optional path for the cache... For now solved by creating the dir w/ required permissions.

**Comment by jeremymcrae** [comment]
I think that's already present? At least, you can pass in a cache folder location to the get_lifter() function, e.g.

``` py
from liftover import get_lifter
get_lifter('hg19', 'hg38', cache='TMP')
```
