### ISSUE TITLE
Difference between rtracklayer?

### ISSUE THREAD

**Issue by xiucz** [jeremymcrae/liftover#18]
Hi, @jeremymcrae 
I am glad to see your `pythonic` liftover tools,  but when  I try to liftover `chr7:61657308`  from  hg19 to hg38, the tools give different results. Can you check the difference here?

Python version
```
>>> converter = get_lifter('hg19', 'hg38')
>>> converter.query("chr7", 61657308)
[('chr7', 62029292, '-')]

>>> converter = ChainFile('~/hg19ToHg38.over.chain', 'hg19', 'hg38')
>>> converter.query("chr7", 61657308)

# it returns chr7:62029292 (hg38version)
```

R version
```
library(GenomicRanges)
library(rtracklayer)
chr<-7;
start<-61657308
chain.file.path<-'~/hg19ToHg38.over.chain'
## convert to Genomic Ranges
example.37.gr<-GRanges(
        seqname=Rle(paste("chr",chr,sep="")),
        ranges=IRanges(start=start,end=start)) 
example.37.gr

c <- import.chain(chain.file.path) ## e.g. hg19ToHg18.over.chain
example.38.gr<-unlist(liftOver(example.37.gr,c))  
example.38.gr

# it returns chr7:62029294 (hg38version)
```
Best, 
xiucz

**Comment by jeremymcrae** [comment]
This tool uses 0-based coordinates, I assume GRanges use 1-based coords. As a result, the two tools can differ in regions where the orientation swaps between builds. See issue #1 as another example with diagram explaining the difference.

The way to fix this is shift your position to 0-based before conversion (i.e. converter.query("chr7", 61657308-1)). That gives a 0-based result (e.g. [('chr7', 62029293, '-')]) which then can be shifted to 1-based (i.e. 62029293+1).
