### ISSUE TITLE
Address changed - 403 forbidden 

### ISSUE THREAD

**Issue by akotlar** [jeremymcrae/liftover#19]
The UCSC URL for liftover chain files appears to have changed, from cse.ucsc.edu -> .soe.ucsc.edu

Old (you get 403 response):
https://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz

New:
https://hgdownload.soe.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz

This utility does not work currently, due to the liftover files being unfetchable

**Comment by jeremymcrae** [comment]
Thanks for catching this! I've updated the package on pypi now.
