### ISSUE TITLE
Support for python2.7

### ISSUE THREAD

**Issue by Yiming-Shen** [jeremymcrae/liftover#2]
Although python2 reached the end of its life on Jan 1st, it is still the only support version for several classic bio packages. I tried to install liftover (by both `pip install liftover` and by `python setup.py build && python setup.py install`) under `python2.7.18` with `cython==0.29.21` but it raised `importError: No module named chain_file` error. I wonder if this fast liftover package is designed for python3+ support?

**Comment by jeremymcrae** [comment]
Whoops, there was a filename conflict which prevented this working in python2. I've uploaded a new version to pypi which should work cleanly under python2/python3.

**Comment by Yiming-Shen** [comment]
Thanks for your work. `liftover==1.1.5` works fine under python2.
