### ISSUE TITLE
KeyError: 'chr1'

### ISSUE THREAD

**Issue by ichauchcc** [jeremymcrae/liftover#7]
Hi Jeremy,

I successfully installed the package, then when I tried to run the example code, I happened to have this error

Traceback (most recent call last):

  File "liftover/chain_file.pyx", line 72, in liftover.chain_file.ChainFile.__getitem__

KeyError: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/yuchen/Desktop/CI-RA/Liftover genome version/liftover_genome_DocFile.py", line 26, in <module>
    converter[chrom][pos]

  File "liftover/chain_file.pyx", line 74, in liftover.chain_file.ChainFile.__getitem__

KeyError: 'chr1'

Is there any idea why is error appear and how may I fix this? Thanks for your time and help.

**Comment by jeremymcrae** [comment]
What genome assemblies are you converting between? Or, what chain file are you using, if you are doing that instead?

It can't find chromosome "1" in converter[chrom], so it then attempts the alternate chromosome ID of "chr1", which also fails. If you're converting between human genome assemblies this should have worked, other species may have lack a chr1 though.

**Comment by ichauchcc** [comment]
Thanks for your quick reply Jermy. I figured out that I am running your sample code without giving it a chain file. I think that's why.
After I run the code without 'ChainFile' part, it runs smoothly.
Sorry for the late reply. Thanks for your answer!
